name: demo-lz-launchpad

on:
  workflow_dispatch:
  
env:
  TF_CLI_ARGS: '-no-color'
  TF_CLI_ARGS_destroy: '-auto-approve -refresh=false'
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ENVIRONMENT: 'demo'
  CAF_ENVIRONMENT: "ajay-demo"
  ROVER_RUNNER: true

jobs:
  launchpad100:
    name: launchpad-100
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
          random_length: ['5']

    container:
      image: aztfmod/rover:1.1.3-2201.2106
      options: --user 0

    steps:
      - uses: actions/checkout@v2
      
      - name: clone the public landing zones
        run: |
          git clone https://github.com/Azure/caf-terraform-landingzones.git /tf/caf/landingzones
      
      - name: Login azure
        run: |
          echo "logging into azure environment..."
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}
          az account show 
          echo "local user: $(whoami)"

      - name: deployLaunchpad100
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/caf_launchpad \
            -var-folder ${GITHUB_WORKSPACE}/configuration/${{ ENVIRONMENT }}/level0/launchpad \
            -launchpad \
            -level level0 \
            -parallelism=30 \
            -env ${{ CAF_ENVIRONMENT }} \ 
            -a apply
            
  